name: Firebase Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: npm run deploy  # Sesuaikan dengan perintah Anda untuk deploy (misalnya, `firebase deploy --only hosting`)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Ganti dengan nama variabel token Firebase Anda dari Secrets
